### ISSUE TITLE
为什么不返回城市编码而返回城市名称

### ISSUE THREAD

**Issue by yuruizhe** [Bigkoo/EasySideBar#1]
如题
绝大多数情况下用户选择城市后需要告知服务器的是城市编码而不是城市名称

**Comment by xiaosong520** [comment]
@yuruizhe 通过回调postion 获取相应数据即可，显示是只需要用到名称的。

**Comment by xiaosong520** [comment]
@yuruizhe  这个可自己做一下扩展， 把数据和回调改动一下就好

**Comment by xiaosong520** [comment]
@yuruizhe  建议引入Module 根据自己需要做定制和细化的逻辑。
